#INCLUDE <P16F84A.INC>  ;LIBRERIA
LIST P=16F84A

ORG 0
    BSF	STATUS,5    ;BANCO 1
    BSF	TRISA,3	    ;PIN A3 ENTRADA
    MOVLW   0X00    ;VALOR 0 EN BINARIO SERIA: MOVLW b'00000000'
    MOVWF   TRISB   ;TODO COMO SALIDA
    BCF	STATUS,5    ;BANCO 0
    GOTO    VERIFICAR

VERIFICAR:
    BTFSS   PORTA,3 ;RA3==1?
    GOTO    PRIMER_MITAD
    GOTO    SEGUNDA_MITAD

PRIMER_MITAD:
    MOVLW   0XF0    ;PRIMERA MITAD DEL PUERTO B EN BINARIO SERIA: MOVLW b'11110000'; TAMBIEN PUEDE SER EN HAX ASI: MOVLW H'F0' Y DEC MOVLW D'10'
    MOVWF   PORTB
    GOTO    VERIFICAR
    
SEGUNDA_MITAD:
    MOVLW   0X0F    ;SEGUNDA MITAD DEL PUERTO B
    MOVWF   PORTB
    GOTO    VERIFICAR
END


