#INCLUDE <P16F84A.INC>
LIST P=16F84A
    
ORG 0
    BSF	    STATUS,5	    ;BANCO 1
    CLRF    TRISB	    ;TODO SALIDA
    BSF	    TRISA,0	    ;A0 ENTRADA
    BCF	    STATUS,5	    ;BANCO 0
    CLRF    PORTB	    ;LIMPIA PUERTO B
    
PROCESO:
    BTFSS   PORTA,0	    ;A0=1?
    GOTO    PROCESO	    ;SI FALSO
    CALL    CONFIRMACION    ;SI VERDADERO
    CALL    PRUEBAC
    GOTO    PROCESO
    
CONFIRMACION:
    BTFSC   PORTA,0	    ;PREGUNTA SI NO SE PULSO A0	;SE COMPORTA COMO UN ANTIRREBOTE
    GOTO    CONFIRMACION    ;FALSO VUELVE A PREGUNTAR	;
    CALL    AUMENTAR	    ;VERDADERO
    RETURN
    
AUMENTAR:
    MOVLW   D'1'	    ;GUARDA EL VALOR DE 1 EN W
    ADDWF   PORTB,1	    ;SUMA EL VALOR DE W EN F (EL PUERTO B)
    RETURN		    ;VUELVE
      
PRUEBAC:
    MOVLW   D'246'	    ;CARGAR EL VALOR DE DESBORDAMIENTO 255-246
    ADDWF   PORTB,0	    ;CON EL ,0 GUARDA EL VALOR EN LA VARIABLE W
    BTFSS   STATUS,C	    ;DETECTA EL ACARREO ES DECIR QUE CUANDO PASE DE 255 C=1
    RETURN		    ;VUELVE
    ANDLW   0XF0	    ;LIMPIA EL PUERTO EN LA PARTE BAJA
    ANDWF   PORTB	    ;ELIJE EL PUERTO B
    RETURN		    ;VUELVE 
   
END


